name: NCPFix
description: Disable NCP under circumstances where it negatively affects enjoyment of the game
author: StarTux
version: 0.1
website: http://cavetale.com
api-version: 1.13
main: com.cavetale.ncpfix.NCPFix
depend: [NoCheatPlus]
softdepend: []
commands:
  ncpfix:
    description: Debug command
    usage: |-
      /ncpfix info - Print info
      /ncpfix debug - Toggle debug (player)
      /ncpfix me - Self info (player)
    permission: ncpfix.ncpfix

permissions:
  ncpfix.ncpfix:
    description: use /ncpfix
    default: op

  ncpfix.remove:
    description: Have your NCP warnings levels reset when you join
    default: false
